# Generated by Django 6.0 on 2026-01-30 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_active_branch'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_branch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='branches',
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
