# Generated by Django 6.0 on 2025-12-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
