# Generated by Django 6.0 on 2026-01-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
