# Generated by Django 6.0 on 2026-01-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_account_balance_remove_account_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('customer', 'Customer')], max_length=10, null=True),
        ),
    ]
