# Generated by Django 6.0 on 2026-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
