# Generated by Django 6.0 on 2026-01-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_account_number_profile_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
