# Generated by Django 6.0 on 2026-01-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disable_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='disable_request',
            field=models.BooleanField(default=False),
        ),
    ]
